### ISSUE TITLE
Redmine Crashes when Clone this repo into plugins folder

### ISSUE THREAD

**Issue by FrancesoM** [maxrossello/redmine_themes#1]
As the title explains, I was trying to use those themes by following the instructions. 
I cloned the pluggable_themes plugin in the plugins folder, then I cloned the redmine_themes repo in the same plugins directory, but redmine crashes. 
Actually I did not understand what is the difference from copying the assets/themes into the public/themes folder. What is the purpose of this plugin? 
Sorry if I have asked a stupid question, I am new to redmine! 
Thanks!!

**Comment by maxrossello** [comment]
Hello,
You may want to attach a trace log and a copy of info available under Administration > Information.

The use cases depicting the advantages from copying to public/themes are described into the redmine_pluggable_themes plugin.

This plugin just exploits redmine_pluggable_themes to provide a selection of best Redmine themes around in one shot, instead of searching/downloading/installing each one separately. This is just after my taste and theme license. So far themes licensed under MIT license or with no explicit license are included. More could come in future (themes licensed GPL 2&3 are possible).

**Comment by maxrossello** [comment]
have you solved your issue or still need support?

**Comment by vanessasoutoc** [comment]
I have the same problem

**Comment by maxrossello** [comment]
dear, if you want support be generous with reporting. Your problem is the same, my answer is the same
thanks

**Comment by maxrossello** [comment]
Ok, found the issue which was not visible with my set of plugins installed. The init.rb looked for a wrong plugin due to a copy/paste.
Sorry for the inconvenient. A report of yours would have helped!
Enjoy.
